### ISSUE TITLE
Object template mesh

### ISSUE THREAD

**Issue by Ale-Burzio** [xiexh20/VisTracker#2]
Great work!

Maybe I am missing something, but how/where is the object template loaded? It's not specified in the dataset preparation section.

Also, does it need to be textured? Are there any other conventions that need to be followed?

**Comment by xiexh20** [comment]
Hi,

Thank you for your interest.
You can find the code to load object template [here](https://github.com/xiexh20/VisTracker/blob/main/behave/utils.py#L190).

At this point, we do not consider object texture. Hence only the vertices and faces are loaded.
