### ISSUE TITLE
About implementation details on InterCap dataset.

### ISSUE THREAD

**Issue by kaenkogashi** [xiexh20/VisTracker#3]
Thanks for your great work!

In your paper, "Visibility Aware Human-Object Interaction Tracking from Single RGB Camera", you train the model on InterCap dataset.
>We train our model on sequences from subject 01-08 (173 sequences) and test on sequences from subject 09-10 (38 sequences).

After I download the InterCap dataset, I found there are 40 sequences from subject 09-10. Did you skip some sequences? Would you tell me why you skipped some sequences?

**Comment by xiexh20** [comment]
Hi, 

Thank you for your interest. I filter the sequences automatically by checking if the RGB images, SMPL and object annotations are complete or not. 
Some sequences do not have SMPL or Object annotation, hence I discard them. For example, there is no SMPL results in `Res/10/05/Seg_0/Mesh`, as far as the data I downloaded.

Hope that clarifies.

Best,
Xianghui

**Comment by kaenkogashi** [comment]
Thanks for your reply.

It looks like SMPL results in Res/10/05/Seg_0/Mesh can be download now.
