### ISSUE TITLE
psbody library 

### ISSUE THREAD

**Issue by Fivesecsofmart** [xiexh20/VisTracker#5]
Hello everyone! 

I'm trying to install all the dependencies, but following the psbody-mesh library READ.me for the requirements, this error appears:

"Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libboost-all-dev is already the newest version (1.74.0.3ubuntu7).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
The virtual environment was not created successfully because ensurepip is not
available. On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

apt install python3.10-venv
You may need to use sudo with that command. After installing the python3-venv
package, recreate your virtual environment.

Failing command: /content/mesh/psbody-mesh-namespace/my_venv/bin/python3

/bin/bash: line 1: my_venv/bin/activate: No such file or directory
Cloning into 'psbody.mesh'...
fatal: could not read Username for 'https://github.com/': No such device or address
[Errno 2] No such file or directory: 'psbody.mesh'
/content/mesh/psbody-mesh-namespace
make: *** No rule to make target 'all'. Stop."

Can anybody help me?

**Comment by xiexh20** [comment]
Hi, sorry for the late reply.

Now I realized that psbody.mesh library is not well maintained anymore. In my code the core function from psbody I used is mainly the Mesh library for mesh loading/export. 

If you don't need the MeshViewer visualizer, then you can simply extract the corresponding source code of psbody and use that as your `Mesh` class. One example script I used can be found here: https://github.com/xiexh20/ProciGen/blob/main/render/mesh.py
