### ISSUE TITLE
Using different videos

### ISSUE THREAD

**Issue by Salvador-Alban** [xiexh20/VisTracker#6]
I am trying to use this model on different footage than the one provided and was curious what steps would be required to prepare the video for the model to process it. In the demo data provided, there is a folder "calibs". Is this the calibrations of the kinects used? What would I need to replace that with if I recorded myself from just one camera? Thank you for your time.

**Comment by xiexh20** [comment]
Hi, sorry for the late reply. 

To run on your own video, you need to provide intrinsics of the camera to capture the video. If unknown, then you can try to resize the image to 2048x1536 (width&height, the same size as behave images). With this then you can run the code with the default behave cameras.

**Comment by Salvador-Alban** [comment]
Thank you for your reply. I've managed to run frankmocap and openpose detections on my own videos but I am not sure what information I should use to create the GT-packed files. What detections should I use for it to run my own videos? Thank you for your time.

**Comment by xiexh20** [comment]
Hi,

Please check run demo(https://github.com/xiexh20/VisTracker?tab=readme-ov-file#run-demo) to download example demo data, which also includes example GT-packed file.
