### ISSUE TITLE
about HPE

### ISSUE THREAD

**Issue by rabbitchenrui** [xiexh20/VisTracker#8]
Thanks for your great work！
 I read the paper from CHORE, and find that you have finished saveral related work....respeact!
 I am very interested in scene information for human behavior, and have a question is that:
 Do object detection or scene understanding can help improved the result such as MPJPE(mean per joint position error) on HPE(human pose estimation) task？
Seeing the excellent work you have done, I am very curious about your answer to this question

**Comment by rabbitchenrui** [comment]
By the way... maybe relative path for some file in open source can work better, I have modified so many path to run VisTracker hhh. Just a small advice..

**Comment by xiexh20** [comment]
Hi, thank you for your interest. 

I would say scene information is very helpful to infer a globally consistent pose, especially dealing with video-based pose estimation. There are lots of excelent works along this line that leverage scene info to help HPE, e.g.: PROX, ICCV'19. MocapDeform, 3DV'21. [Probabilistic Human Mesh Recovery in 3D Scenes from Egocentric Views](https://sanweiliti.github.io/egohmr/egohmr.html). 

Object detection would also be helpful, similar to the idea used in VisTracker: we can use the human pose to infer occluded objects. We can also use the detected object to infer the local pose of the occluded body part. This is less explored as far as I know. Or these information are learned implicitely by adding occlusion augmentation to the training data. e.g. the AGORA and BEDLEM dataset. 

About the relative path: good suggestion! and sorry for the inconvenience : ). I use lots of preprocessed files in this project so it was convenient for me to just set the abs path and also to avoid having large files in the same project directory. But you are right, for open sourcing a relative path is better.
